=== namlehong/ertheia/dist/gameserver/data/l2on_droplist/DropListData.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT list (npc)*>
<!ELEMENT npc (droplist|spoillist)*>
<!ATTLIST npc
	id CDATA #REQUIRED>
<!ELEMENT droplist (category)*>
<!ELEMENT category (item)*>
<!ATTLIST category
	chance CDATA #IMPLIED
	id CDATA #IMPLIED>
<!ELEMENT spoillist (item)*>
<!ELEMENT item (#PCDATA)>
<!ATTLIST item
	chance CDATA #REQUIRED
	id CDATA #REQUIRED
	max CDATA #REQUIRED
	min CDATA #REQUIRED>

=== namlehong/ertheia/dist/gameserver/data/l2on_droplist/35700-35799.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE list SYSTEM "DropListData.dtd">
<list>
  <npc id="35702">
    <droplist>
      <category chance="33.3333">
        <item chance="100.0000" id="9581" max="1" min="1" />
      </category>
    </droplist>
  </npc>
  <npc id="35711">
    <droplist>
      <category chance="25.7962">
        <item chance="100.0000" id="10014" max="1" min="1" />
      </category>
    </droplist>
  </npc>
  <npc id="35734">
    <droplist>
      <category chance="53.3333">
        <item chance="100.0000" id="36309" max="145" min="102" />
      </category>
    </droplist>
  </npc>
  <npc id="35766">
    <droplist>
      <category chance="52.3809">
        <item chance="100.0000" id="36309" max="144" min="107" />
      </category>
    </droplist>
  </npc>
  <npc id="35780">
    <droplist>
      <category chance="21.0027">
        <item chance="100.0000" id="10014" max="1" min="1" />
      </category>
    </droplist>
  </npc>
</list>

=== namlehong/ertheia/dist/gameserver/data/l2on_droplist/20300-20399.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE list SYSTEM "DropListData.dtd">
<list>
  <npc id="20308">
    <droplist>
      <category chance="79.1667">
        <item chance="100.0000" id="57" max="66" min="32" />
      </category>
    </droplist>
    <spoillist>
      <item chance="28.5714" id="36531" max="1" min="1" />
    </spoillist>
  </npc>
  <npc id="20314">
    <droplist>
      <category chance="0.0055">
        <item chance="100.0000" id="36562" max="1" min="1" />
      </category>
      <category chance="0.0750">
        <item chance="50.0000" id="36522" max="1" min="1" />
        <item chance="50.0000" id="36537" max="1" min="1" />
      </category>
      <category chance="0.3000">
        <item chance="50.0000" id="36527" max="1" min="1" />
        <item chance="50.0000" id="36517" max="1" min="1" />
      </category>
      <category chance="4.5454">
        <item chance="100.0000" id="57" max="154" min="154" />
      </category>
      <category chance="0.0300">
        <item chance="25.0000" id="36552" max="1" min="1" />
        <item chance="25.0000" id="36542" max="1" min="1" />
        <item chance="25.0000" id="36557" max="1" min="1" />
        <item chance="25.0000" id="36547" max="1" min="1" />
      </category>
    </droplist>
    <spoillist>
      <item chance="35.5100" id="36531" max="1" min="1" />
      <item chance="0.0030" id="36880" max="1" min="1" />
    </spoillist>
  </npc>
  <npc id="20325">
    <droplist>
      <category chance="1.3158">
        <item chance="100.0000" id="1060" max="1" min="1" />
      </category>
      <category chance="39.8026">
        <item chance="100.0000" id="57" max="27" min="7" />
      </category>
    </droplist>
    <spoillist>
      <item chance="0.6452" id="36561" max="1" min="1" />
    </spoillist>
  </npc>
  <npc id="20330">
    <droplist>
      <category chance="7.9208">
        <item chance="100.0000" id="36521" max="1" min="1" />
      </category>
      <category chance="66.3366">
        <item chance="100.0000" id="57" max="46" min="21" />
      </category>
    </droplist>
    <spoillist>
      <item chance="22.7273" id="36521" max="1" min="1" />
    </spoillist>
  </npc>
  <npc id="20331">
    <droplist>
      <category chance="3.7037">
        <item chance="100.0000" id="36521" max="1" min="1" />
      </category>
      <category chance="66.6667">
        <item chance="100.0000" id="57" max="42" min="19" />
      </category>
    </droplist>
    <spoillist>
      <item chance="10.0000" id="36521" max="1" min="1" />
    </spoillist>
  </npc>
  <npc id="20335">
    <droplist>
      <category chance="1.1220">
        <item chance="100.0000" id="734" max="1" min="1" />
      </category>
      <category chance="0.7500">
        <item chance="100.0000" id="36561" max="1" min="1" />
      </category>
      <category chance="67.2414">
        <item chance="100.0000" id="57" max="69" min="30" />
      </category>
    </droplist>
    <spoillist>
      <item chance="19.3100" id="36531" max="1" min="1" />
    </spoillist>
  </npc>
  <npc id="20336">
    <droplist>
      <category chance="0.9804">
        <item chance="100.0000" id="1060" max="1" min="1" />
      </category>
      <category chance="12.7451">
        <item chance="100.0000" id="57" max="35" min="17" />
      </category>
    </droplist>
    <spoillist>
      <item chance="16.6667" id="36531" max="1" min="1" />
    </spoillist>
  </npc>
  <npc id="20345">
    <droplist>
      <category chance="22.2222">
        <item chance="100.0000" id="1831" max="1" min="1" />
      </category>
      <category chance="62.2222">
        <item chance="100.0000" id="57" max="63" min="28" />
      </category>
    </droplist>
    <spoillist>
      <item chance="18.1818" id="36531" max="1" min="1" />
    </spoillist>
  </npc>
  <npc id="20346">
    <droplist>
      <category chance="59.6491">
        <item chance="100.0000" id="57" max="56" min="24" />
      </category>
    </droplist>
  </npc>
  <npc id="20351">
    <droplist>
      <category chance="63.6364">
        <item chance="100.0000" id="57" max="61" min="28" />
      </category>
    </droplist>
  </npc>
  <npc id="20353">
    <droplist>
      <category chance="75.0000">
        <item chance="100.0000" id="57" max="59" min="59" />
      </category>
    </droplist>
  </npc>
  <npc id="20356">
    <droplist>
      <category chance="0.0030">
        <item chance="100.0000" id="36872" max="1" min="1" />
      </category>
      <category chance="0.7500">
        <item chance="100.0000" id="36527" max="1" min="1" />
      </category>
      <category chance="53.2467">
        <item chance="100.0000" id="57" max="119" min="54" />
      </category>
    </droplist>
    <spoillist>
      <item chance="56.0500" id="36526" max="3" min="1" />
    </spoillist>
  </npc>
  <npc id="20357">
    <droplist>
      <category chance="0.0009">
        <item chance="100.0000" id="36864" max="1" min="1" />
      </category>
      <category chance="0.3000">
        <item chance="100.0000" id="36522" max="1" min="1" />
      </category>
      <category chance="62.9213">
        <item chance="100.0000" id="57" max="102" min="43" />
      </category>
    </droplist>
    <spoillist>
      <item chance="37.5000" id="36521" max="1" min="1" />
    </spoillist>
  </npc>
  <npc id="20358">
    <droplist>
      <category chance="0.0009">
        <item chance="100.0000" id="36866" max="1" min="1" />
      </category>
      <category chance="2.4390">
        <item chance="100.0000" id="36521" max="1" min="1" />
      </category>
      <category chance="59.5122">
        <item chance="100.0000" id="57" max="72" min="32" />
      </category>
    </droplist>
    <spoillist>
      <item chance="0.7500" id="36522" max="1" min="1" />
    </spoillist>
  </npc>
  <npc id="20359">
    <droplist>
      <category chance="0.0009">
        <item chance="100.0000" id="36563" max="1" min="1" />
      </category>
      <category chance="0.0750">
        <item chance="100.0000" id="33" max="1" min="1" />
      </category>
      <category chance="0.0300">
        <item chance="100.0000" id="27" max="1" min="1" />
      </category>
      <category chance="28.5714">
        <item chance="100.0000" id="57" max="48" min="41" />
      </category>
    </droplist>
    <spoillist>
      <item chance="10.5600" id="36531" max="1" min="1" />
      <item chance="0.0300" id="36533" max="1" min="1" />
    </spoillist>
  </npc>
  <npc id="20360">
    <droplist>
      <category chance="0.0009">
        <item chance="100.0000" id="36866" max="1" min="1" />
      </category>
      <category chance="3.8462">
        <item chance="100.0000" id="36521" max="1" min="1" />
      </category>
      <category chance="62.3932">
        <item chance="100.0000" id="57" max="67" min="29" />
      </category>
    </droplist>
    <spoillist>
      <item chance="0.3000" id="36522" max="1" min="1" />
    </spoillist>
  </npc>
  <npc id="20369">
    <droplist>
      <category chance="0.2525">
        <item chance="50.0000" id="36562" max="1" min="1" />
        <item chance="50.0000" id="36561" max="1" min="1" />
      </category>
      <category chance="68.1818">
        <item chance="100.0000" id="57" max="69" min="29" />
      </category>
    </droplist>
  </npc>
  <npc id="20371">
    <droplist>
      <category chance="65.6250">
        <item chance="100.0000" id="57" max="54" min="26" />
      </category>
    </droplist>
    <spoillist>
      <item chance="33.3333" id="36531" max="1" min="1" />
    </spoillist>
  </npc>
  <npc id="20372">
    <droplist>
      <category chance="1.7544">
        <item chance="100.0000" id="36561" max="1" min="1" />
      </category>
      <category chance="1.1696">
        <item chance="100.0000" id="36541" max="1" min="1" />
      </category>
      <category chance="66.0819">
        <item chance="100.0000" id="57" max="42" min="18" />
      </category>
    </droplist>
    <spoillist>
      <item chance="11.7647" id="36531" max="1" min="1" />
    </spoillist>
  </npc>
  <npc id="20373">
    <droplist>
      <category chance="1.6129">
        <item chance="100.0000" id="36551" max="1" min="1" />
      </category>
      <category chance="70.9677">
        <item chance="100.0000" id="57" max="46" min="20" />
      </category>
    </droplist>
    <spoillist>
      <item chance="9.3023" id="36531" max="1" min="1" />
    </spoillist>
  </npc>
  <npc id="20389">
    <droplist>
      <category chance="66.6667">
        <item chance="100.0000" id="57" max="55" min="31" />
      </category>
    </droplist>
  </npc>
  <npc id="20393">
    <droplist>
      <category chance="74.0260">
        <item chance="100.0000" id="57" max="66" min="29" />
      </category>
    </droplist>
  </npc>
</list>
