=== namlehong/ertheia/dist/gameserver/data/blood/fp_item.dtd
<!ELEMENT list (reward)*>
<!ELEMENT reward (#PCDATA|reward|classid|classtype|classtype2|item|remove_item)*>
<!ATTLIST reward
	name CDATA #REQUIRED
	parent CDATA #IMPLIED
	weight CDATA #IMPLIED
	min_level CDATA #IMPLIED
	max_level CDATA #IMPLIED>

<!ELEMENT classid (#PCDATA)>
<!ATTLIST classid
	value CDATA #REQUIRED>
	
<!ELEMENT classtype (#PCDATA)>
<!ATTLIST classtype
	value CDATA #REQUIRED>
	
<!ELEMENT classtype2 (#PCDATA)>
<!ATTLIST classtype2
	value CDATA #REQUIRED>
		
<!ELEMENT item (#PCDATA)>
<!ATTLIST item
	id CDATA #REQUIRED
	count CDATA #REQUIRED>

<!ELEMENT remove_item (#PCDATA)>
<!ATTLIST remove_item
	id CDATA #REQUIRED>

=== namlehong/ertheia/dist/gameserver/data/blood/fp_item2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "fp_item.dtd">
<list>
	<reward name='Common'>
		<item id='6645' count='2000'/> <!-- Beast soulshot -->
		<item id='6647' count='2000'/> <!-- Beast BSS -->
		<item id='3031' count='2000'/> <!-- Spirit Ore -->
	</reward>
	<reward name='D-Common' parent='Common' min_level='1' max_level='19'>
		<item id="14975" count="2"/>
		<item id="14976" count="1"/>
		<item id="14977" count="2"/>
		<item id="3948" count="2000"/> 	<!--Blessed Spiritshot (D-grade)-->
		<item id="21846" count="2000"/> <!--Soulshot D grade-->
	</reward>
	<reward name='D-Light' parent='D-Common'>
		<item id="15017" count="1"/>	<!--Malticore Skin shirt-->
		<item id="15018" count="1"/>
		<item id="15019" count="1"/>
		<item id="15020" count="1"/>
		<item id="15023" count="1"/>
	</reward>
	<reward name='D-Heavy' parent='D-Common'>
		<item id="15021" count="1"/>	<!--Bringedai-->
		<item id="15022" count="1"/>
		<item id="15023" count="1"/>
		<item id="15024" count="1"/>
		<item id="15025" count="1"/>
	</reward>
	<reward name='D-Magic' parent='D-Common'>
		<item id="14992" count="1"/>	<!--Mithril Tunic set-->
		<item id="14993" count="1"/>
		<item id="14994" count="1"/>
		<item id="14995" count="1"/>
		<item id="15023" count="1"/>
	</reward>
	<reward name="D-Archer" parent="D-Light">
		<classtype value="FIGHTER"/>
		<item id="15043" count="1"/> 	<!--Light Crossbow of Fortune 30-day-->
		<item id="32250" count="1"/> 	<!--Infinite Bone Quiver-->
	</reward>
	<reward name="D-Wizard" parent="D-Robe">
		<classtype value="MYSTIC"/>
		<item id="15035" count="1"/> 	<!--Staff of Life of Fortune 30-day-->
		<item id="15026" count="1"/>
	</reward>
	<reward name='D-crossbow' parent='D-Light'>
		<classid name='TRICKSTER'/>
		<classid name='ARBALESTER'/>
		<classid name='WARDER'/>
		<item id="15079" count="1"/> 	<!--Crossbow D of Fortune 30-day-->
	</reward>
	<reward name='C-Common' parent='Common' min_level='40' max_level='51'>
		<item id="14972" count="2"/> 	<!--Sealed Rings set-->
		<item id="14973" count="1"/>
		<item id="14974" count="2"/>
		<item id="21853" count="2000"/> <!--Blessed Spiritshot (C-grade)-->
		<item id="21847" count="2000"/> <!--Soulshot C grade-->
	</reward>
	<reward name='C-Light' parent='C-Common'>
		<item id="15008" count="1"/>	<!--Plated set-->
		<item id="15009" count="1"/>
		<item id="15010" count="1"/>
		<item id="15011" count="1"/>
	</reward>
	<reward name='C-Heavy' parent='C-Common'>
		<item id="15012" count="1"/>	<!--Full plated set-->
		<item id="15013" count="1"/>
		<item id="15014" count="1"/>
		<item id="15015" count="1"/>
	</reward>
	<reward name='C-Magic' parent='C-Common'>
		<item id="14988" count="1"/>	<!--Karmian set-->
		<item id="14989" count="1"/>
		<item id="14990" count="1"/>
		<item id="14991" count="1"/>
		<item id="15012" count="1"/>
	</reward>
	<reward name='C-Homu' parent='C-Magic'>
		<classtype name="MYSTIC"/>
		<item id="15034" count="1"/> 	<!--Homu of Fortune 30-day-->
		<item id="15016" count="1"/>
	</reward>
	<reward name='C-Dagger' parent='C-Light'>
		<classtype2 name='ROGUE'/>
		<item id="15038" count="1"/> 	<!--Dark Screamer of Fortune 30-day-->
	</reward>
	<reward name='C-Bow' parent='C-Light'>
		<classtype name="FIGHTER"/>
		<classtype2 name='ARCHER'/>
		<item id="15042" count="1"/> 	<!--Bow of Emi of Fortune 30-day-->
		<item id="32251" count="1"/> 	<!--Infinite Steel Quiver-->
	</reward>
	<reward name='C-blunt' parent='C-Heavy'>
		<classtype2 name='KNIGHT'/>
		<item id="15046" count="1"/> 	<!--Yaska Axe of Fortune 30-day-->
		<item id="15016" count="1"/>
	</reward>
	<reward name='C-Sword' parent='C-Heavy'>
		<classtype2 name='KNIGHT'/>
		<item id="15050" count="1"/> 	<!--Samurai Long Sword of Fortune 30-day-->
		<item id="15016" count="1"/>
	</reward>
	<reward name='C-2h' parent='C-Heavy'>
		<classid name='DESTROYER'/>
		<classid name='TITAN'/>
		<item id="15054" count="1"/> 	<!--2h Sword C of Fortune 30-day-->
	</reward>
	<reward name='C-fists' parent='C-Heavy'>
		<classid name='TYRANT'/>
		<classid name='GRAND_KHAVATARI'>
		<item id="15058" count="1"/> 	<!--Fist C of Fortune 30-day-->
	</reward>
	<reward name='C-dual' parent='C-Heavy'>
		<classtype2 name='WARRIOR'/>
		<classid name='GLADIATOR'/>
		<classid name='DUELIST'/>
		<classid name='BLADEDANCER'/>
		<classid name='SPECTRAL_DANCER'>
		<item id="15062" count="1"/> 	<!--Dual C of Fortune 30-day-->
	</reward>
	<reward name='C-pole' parent='C-Heavy'>
		<classid name='DESTROYER'/>
		<classid name='TITAN'/>
		<classid name='WARLORD'/>
		<classid name='DREADNOUGHT'/>
		<item id="15066" count="1"/> 	<!--Pole C of Fortune 30-day-->
	</reward>
	<reward name='C-Acient' parent='C-Heavy'>
		<classid name='BERSERKER'/>
		<classid name='DOOMBRINGER'/>
		<item id="15070" count="1"/> 	<!--Ancient Sword C of Fortune 30-day-->
	</reward>
	<reward name='C-rapier' parent='C-Magic'>
		<classid name='M_SOUL_HOUND'>
		<classid name='F_SOUL_HOUND'>
		<classid name='M_SOUL_BREAKER'>
		<classid name='F_SOUL_BREAKER'>
		<item id="15074" count="1"/> 	<!--Rapier C of Fortune 30-day-->
	</reward>
	<reward name='C-Crossbow' parent='C-Light'>
		<classid name='TRICKSTER'/>
		<classid name='ARBALESTER'/>
		<classid name='WARDER'/>
		<item id="15078" count="1"/> 	<!--Crossbow C of Fortune 30-day-->
	</reward>
	<reward name='B-Common' parent='Common' min_level='52' max_level='61'>
		<item id="14969" count="2"/> 	<!--Black Ore Rings set-->
		<item id="14970" count="1"/>
		<item id="14971" count="2"/>
		<item id="21848" count="2000"/><!--Soulshot B grade-->
		<item id="21854" count="2000"/> <!--Blessed Spiritshot (B-grade)-->
	</reward>
	<reward name='B-Light' parent='B-Common'>
		<item id="15000" count="1"/>	<!--Doom Light set-->
		<item id="15003" count="1"/>
		<item id="15005" count="1"/>
		<item id="15001" count="1"/>
	</reward>
	<reward name='B-Heavy' parent='B-Common'>
		<item id="15006" count="1"/>	<!--Doom heavy set-->
		<item id="15002" count="1"/>
		<item id="15004" count="1"/>
		<item id="15001" count="1"/>
	</reward>
	<reward name='B-Magic' parent='B-Common'>
		<item id="14983" count="1"/>	<!--Avadon set-->
		<item id="14985" count="1"/>
		<item id="14986" count="1"/>
		<item id="15001" count="1"/>
		<item id="14987" count="1"/>
	</reward>
	<reward name='B-WIZARD' parent='B-Magic'>
		<classtype2 name='WIZARD'/>
		<classtype name="MYSTIC"/>
		<item id="15033" count="1"/> 	<!--Wizzard Tear of Fortune 30-day-->
	</reward>
	<reward name='B-Dagger' parent='B-Light'>
		<classtype2 name='ROGUE'/>
		<item id="15037" count="1"/> 	<!--Kris of Fortune 30-day-->
	</reward>
	<reward name='B-Bow' parent='B-Light'>
		<classtype2 name='ARCHER'/>
		<item id="15041" count="1"/> 	<!--Bow of Peril of Fortune 30-day-->
		<item id="32252" count="1"/> 	<!--Infinite Silver Quiver-->
	</reward>
	<reward name='B-blunt' parent='B-Heavy'>
		<classtype2 name='KNIGHT'/>
		<item id='15045' count='1'/> <!-- B - KNIGHT - blunt -->
		<item id="15007" count="1"/>
	</reward>
	<reward name='B-Sword' parent='B-Heavy'>
		<classtype2 name='KNIGHT'/>
		<item id="15049" count="1"/> 	<!--Damacus of Fortune 30-day-->
		<item id="15007" count="1"/>
	</reward>
	<reward name='B-2h' parent='B-Heavy'>
		<classid name='DESTROYER'/>
		<classid name='TITAN'/>
		<item id="15053" count="1"/> 	<!--2h Sword B of Fortune 30-day-->
	</reward>
	<reward name='B-fists' parent='B-Heavy'>
		<classid name='TYRANT'/>
		<classid name='GRAND_KHAVATARI'>
		<item id="15057" count="1"/> 	<!--Fist B of Fortune 30-day-->
	</reward>
	<reward name='B-dual' parent='B-Heavy'>
		<classid name='GLADIATOR'/>
		<classid name='DUELIST'/>
		<classid name='BLADEDANCER'/>
		<classid name='SPECTRAL_DANCER'>
		<item id="15061" count="1"/> 	<!--Dual B of Fortune 30-day-->
	</reward>
	<reward name='B-pole' parent='B-Heavy'>
		<classtype2 name='WARRIOR'/>
		<classid name='DESTROYER'/>
		<classid name='TITAN'/>
		<classid name='WARLORD'/>
		<classid name='DREADNOUGHT'/>
		<item id="15065" count="1"/> 	<!--Pole B of Fortune 30-day-->
	</reward>
	<reward name='B-Acient' parent='B-Heavy'>
		<classid name='BERSERKER'/>
		<classid name='DOOMBRINGER'/>
		<item id="15069" count="1"/> 	<!--Ancient Sword B of Fortune 30-day-->
	</reward>
	<reward name='B-rapier' parent='B-Magic'>
		<classid name='M_SOUL_HOUND'>
		<classid name='F_SOUL_HOUND'>
		<classid name='M_SOUL_BREAKER'>
		<classid name='F_SOUL_BREAKER'>
		<item id="15073" count="1"/> 	<!--Rapier B of Fortune 30-day-->
	</reward>
	<reward name='B-crossbow' parent='B-Light'>
		<classid name='TRICKSTER'/>
		<classid name='ARBALESTER'/>
		<classid name='WARDER'/>
		<item id="15077" count="1"/> 	<!--Crossbow B of Fortune 30-day-->
	</reward>
	<reward name='A-Common' parent='Common' min_level='61' max_level='75'>
		<item id="14968" count="2"/> 	<!--Majestic Rings set-->
		<item id="14967" count="1"/>
		<item id="14966" count="2"/>
		<item id="21855" count="2000"/> <!--Blessed Spiritshot (A-grade)-->
		<item id="21849" count="2000"/><!--Soulshot A grade-->
	</reward>
	<reward name='A-Light' parent='A-Common'>
		<item id="14996" count="1"/>	<!--Dark Crystal Leather set-->
		<item id="14998" count="1"/>
		<item id="14997" count="1"/>
		<item id="14999" count="1"/>
		<item id="14979" count="1"/>
	</reward>
	<reward name='A-Heavy' parent='A-Common'>
		<item id="15027" count="1"/>	<!--Nightmare heavy set-->
		<item id="15029" count="1"/>
		<item id="15030" count="1"/>
		<item id="15028" count="1"/>
	</reward>
	<reward name='A-Magic' parent='A-Common'>
		<item id="14978" count="1"/>	<!--Dark Crystal set-->
		<item id="14980" count="1"/>
		<item id="14981" count="1"/>
		<item id="14979" count="1"/>
		<item id="14982" count="1"/>
	</reward>
	<reward name='A-SoM' parent='A-Magic'>
		<classtype2 name='WIZARD'/>
		<item id="15032" count="1"/> 	<!--Sword of Miracles of Fortune 30-day-->
	</reward>
	<reward name='A-Dagger' parent='A-Light'>
		<classtype2 name='ROGUE'/>
		<item id="15036" count="1"/> 	<!--Naga Storm (dagger) of Fortune 30-day-->
	</reward>
